# Busca as categorias
GET http://localhost:3000/categories
Content-Type: application/json
###


# Inclui uma nova categoria
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiZmVybmFuZG8ubWFyYW5zYXR0b0BnbWFpbC5jb20iLCJpYXQiOjE2MjQ5ODk5MzIsImV4cCI6MTYyNDk5MzUzMn0.8yrR4tfNdtR99NwoZUJ6vVRK9d8tk7iWngOxI4A62Lc

{
    "name" : "Roupas"
}
###
