# Cadastra um Usuário
POST http://localhost:3000/users
Content-Type: application/json

{
    "email" : "fernando.maransatto@gmail.com",
    "password" : "maransatto"
}

###

# Faz o login do usuário
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "fernando.maransatto@gmail.com",
    "password" : "maransatto"
}
###

